### PR TITLE
Split `write_dwc()` and create helper functions

### PR DESCRIPTION
**Pull request by sangovae**
### Fixing #57 

`write_dwc()` is split into `write_dwc()` and `write_eml()`
- test files are updates
- snapshots were moved
- documentation is updated
- helper functions were added for testing `write_eml()`

`write_eml()` is also a function of `EML`.  Should be keep this name or change it to something unique?
Eg. `write_dwc_csv()` and `write_dwc_eml()`?

### Fixing #66 

Two helper functions were created for  `write_dwc()`:
- `dwc_occurrence_ref()`
- `dwc_occurrence_gps()`

### CODE REVIEW

**Comment by sangovae** [comment]
One test failed, but I don't understand what the problem is...

**Comment by peterdesmet** [comment]
> write_eml() is also a function of EML. Should be keep this name or change it to something unique?
Eg. write_dwc_csv() and write_dwc_eml()?

I would keep that name for now. The more annoying function that has the same name is `add_resource()`, which masks `add_resource()` in frictionless (originally by design).

**Review by peterdesmet — APPROVED** [review]
Nice work!

I've currently already updated the function documentation to indicate that an meta.xml and that data are returned invisibly, cf. https://github.com/inbo/movepub/issues/71 so it would be good to not linger to much on implementing that one.

But thought it better to review and accept this PR separately.

**Comment by sangovae** [comment]
Do you want meta.xml also to be returned invisibly?
It is currently only copied from /extdata, so it it never a data frame in the function. In camptrapdp, meta.xml is also not returned.

**Comment by peterdesmet** [comment]
No, it's a hierarchical data structure (i.e. a list), not a data frame, so I wouldn't return it.

**Pull request merged**
